title: "Transformer PhysX"
description: "Transformers for modeling physical systems"
url: 
baseurl: "https://zabaras.github.io/transformer-physx/"
author: "Nick Geneva"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs