# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-assets 

exclude:
  - src

title: Transformer-PhysX
description: Transformers for modeling physical systems
# email: 
# description: >- # this means to ignore newlines until "baseurl:"
#   Transformers for modeling physical systems.
baseurl: "/phys-transformers" # the subpath of your site, e.g. /blog
url: "https://nicholasgeneva.com/phys-transformers/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NickGeneva
github_username:  NickGeneva

sass:
  style: compressed # Style compression

# 9. Site navigation
navigation_header:
- title: Github
  url: https://github.com/zabaras/transformer-physx
- title: Documentation
  url: https://transformer-physx.readthedocs.org/en/latest/
- title: Data
  url: https://zenodo.org/

remote_theme: daviddarnes/alembic
